//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpieleSammlung.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpieleSammlung.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string ConfirmationWindow_Cancel {
            get {
                return ResourceManager.GetString("ConfirmationWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ConfirmationWindow_ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmationWindow_ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string ConfirmationWindow_title {
            get {
                return ResourceManager.GetString("ConfirmationWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du wirklich das Spiel verlassen?.
        /// </summary>
        public static string ConfirmLeave_Message {
            get {
                return ResourceManager.GetString("ConfirmLeave_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string Connect4_NewGame {
            get {
                return ResourceManager.GetString("Connect4_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wechseln.
        /// </summary>
        public static string Connect4_SwitchStartPlayer {
            get {
                return ResourceManager.GetString("Connect4_SwitchStartPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weiter.
        /// </summary>
        public static string Knif_Btn_NextPlayer {
            get {
                return ResourceManager.GetString("Knif_Btn_NextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neu würfeln.
        /// </summary>
        public static string Knif_Btn_Reshuffle {
            get {
                return ResourceManager.GetString("Knif_Btn_Reshuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler Nummer: .
        /// </summary>
        public static string Knif_Lbl_PlayerNumber {
            get {
                return ResourceManager.GetString("Knif_Lbl_PlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verbleibende Versuche: .
        /// </summary>
        public static string Knif_Lbl_RemainingShuffle {
            get {
                return ResourceManager.GetString("Knif_Lbl_RemainingShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streichen.
        /// </summary>
        public static string Knif_Lbl_RemoveField {
            get {
                return ResourceManager.GetString("Knif_Lbl_RemoveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runde: .
        /// </summary>
        public static string Knif_Lbl_Round {
            get {
                return ResourceManager.GetString("Knif_Lbl_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eintragen.
        /// </summary>
        public static string Knif_Lbl_WriteField {
            get {
                return ResourceManager.GetString("Knif_Lbl_WriteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to große Straße.
        /// </summary>
        public static string Knif_PointsTable_BigStreet {
            get {
                return ResourceManager.GetString("Knif_PointsTable_BigStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus ab 63 Punkten.
        /// </summary>
        public static string Knif_PointsTable_Bonus {
            get {
                return ResourceManager.GetString("Knif_PointsTable_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        public static string Knif_PointsTable_Chance {
            get {
                return ResourceManager.GetString("Knif_PointsTable_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full House.
        /// </summary>
        public static string Knif_PointsTable_FullHouse {
            get {
                return ResourceManager.GetString("Knif_PointsTable_FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kniffel.
        /// </summary>
        public static string Knif_PointsTable_Kniffel {
            get {
                return ResourceManager.GetString("Knif_PointsTable_Kniffel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreierpasch.
        /// </summary>
        public static string Knif_PointsTable_PairSize3 {
            get {
                return ResourceManager.GetString("Knif_PointsTable_PairSize3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viererpasch.
        /// </summary>
        public static string Knif_PointsTable_PairSize4 {
            get {
                return ResourceManager.GetString("Knif_PointsTable_PairSize4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kleine Straße.
        /// </summary>
        public static string Knif_PointsTable_SmallStreet {
            get {
                return ResourceManager.GetString("Knif_PointsTable_SmallStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        public static string Knif_PointsTable_Sum {
            get {
                return ResourceManager.GetString("Knif_PointsTable_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe unterer Teil.
        /// </summary>
        public static string Knif_PointsTable_SumBottom {
            get {
                return ResourceManager.GetString("Knif_PointsTable_SumBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe oberer Teil.
        /// </summary>
        public static string Knif_PointsTable_SumTop {
            get {
                return ResourceManager.GetString("Knif_PointsTable_SumTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er.
        /// </summary>
        public static string Knif_PointsTable_Top6AdditionEndOfNumber {
            get {
                return ResourceManager.GetString("Knif_PointsTable_Top6AdditionEndOfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        public static string Knif_PointsVisual_Lbl_Sum {
            get {
                return ResourceManager.GetString("Knif_PointsVisual_Lbl_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe unterer Teil.
        /// </summary>
        public static string Knif_PointsVisual_Lbl_SumBottom {
            get {
                return ResourceManager.GetString("Knif_PointsVisual_Lbl_SumBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1er.
        /// </summary>
        public static string KnifPointsVisual_Lbl_1 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2er.
        /// </summary>
        public static string KnifPointsVisual_Lbl_2 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3er.
        /// </summary>
        public static string KnifPointsVisual_Lbl_3 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4er.
        /// </summary>
        public static string KnifPointsVisual_Lbl_4 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5er.
        /// </summary>
        public static string KnifPointsVisual_Lbl_5 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6er.
        /// </summary>
        public static string KnifPointsVisual_Lbl_6 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to große Straße.
        /// </summary>
        public static string KnifPointsVisual_Lbl_BigStreet {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_BigStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus ab 63 Punkten.
        /// </summary>
        public static string KnifPointsVisual_Lbl_BonusTop {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_BonusTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        public static string KnifPointsVisual_Lbl_Chance {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full House.
        /// </summary>
        public static string KnifPointsVisual_Lbl_FullHouse {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kniffel.
        /// </summary>
        public static string KnifPointsVisual_Lbl_Kniffel {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_Kniffel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreierpasch.
        /// </summary>
        public static string KnifPointsVisual_Lbl_Pair3 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_Pair3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viererpasch.
        /// </summary>
        public static string KnifPointsVisual_Lbl_Pair4 {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_Pair4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kleine Straße.
        /// </summary>
        public static string KnifPointsVisual_Lbl_SmallStreet {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_SmallStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe oberer Teil.
        /// </summary>
        public static string KnifPointsVisual_Lbl_SumTop {
            get {
                return ResourceManager.GetString("KnifPointsVisual_Lbl_SumTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel Verlassen.
        /// </summary>
        public static string Main_Btn_LeaveMatch {
            get {
                return ResourceManager.GetString("Main_Btn_LeaveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Main_LeavePlayerCreator {
            get {
                return ResourceManager.GetString("Main_LeavePlayerCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen für gewählten Spieler.
        /// </summary>
        public static string ML_Lbl_ActionForSelectedPlayer {
            get {
                return ResourceManager.GetString("ML_Lbl_ActionForSelectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Spieleranzahl:.
        /// </summary>
        public static string ML_Lbl_CurrentPlayerCount {
            get {
                return ResourceManager.GetString("ML_Lbl_CurrentPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Spieleranzahl:.
        /// </summary>
        public static string ML_Lbl_MaxPlayerCount {
            get {
                return ResourceManager.GetString("ML_Lbl_MaxPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale Spieleranzahl:.
        /// </summary>
        public static string ML_Lbl_MinPlayerCount {
            get {
                return ResourceManager.GetString("ML_Lbl_MinPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler kicken.
        /// </summary>
        public static string ML_Lbl_RemovePlayer {
            get {
                return ResourceManager.GetString("ML_Lbl_RemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler umbennen.
        /// </summary>
        public static string ML_Lbl_RenamePlayer {
            get {
                return ResourceManager.GetString("ML_Lbl_RenamePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf weitere Spieler warten.
        /// </summary>
        public static string ML_Lbl_WaitForOtherPlayers {
            get {
                return ResourceManager.GetString("ML_Lbl_WaitForOtherPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Match.
        /// </summary>
        public static string MP_Btn_JoinMatch {
            get {
                return ResourceManager.GetString("MP_Btn_JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum Host wird hergestellt.
        /// </summary>
        public static string MP_ConnectionToHost {
            get {
                return ResourceManager.GetString("MP_ConnectionToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-Adresse des Hosts.
        /// </summary>
        public static string MP_HostIp {
            get {
                return ResourceManager.GetString("MP_HostIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Match.
        /// </summary>
        public static string MP_HostMatch {
            get {
                return ResourceManager.GetString("MP_HostMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portnummer des Hosts.
        /// </summary>
        public static string MP_HostPort {
            get {
                return ResourceManager.GetString("MP_HostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match beitreten.
        /// </summary>
        public static string MP_JoinMatch {
            get {
                return ResourceManager.GetString("MP_JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Connection to Host.
        /// </summary>
        public static string MP_LostConnectionToHost {
            get {
                return ResourceManager.GetString("MP_LostConnectionToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MP_Name {
            get {
                return ResourceManager.GetString("MP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string MP_Port {
            get {
                return ResourceManager.GetString("MP_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel starten.
        /// </summary>
        public static string MP_StartMatch {
            get {
                return ResourceManager.GetString("MP_StartMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auf weitere Spieler warten.
        /// </summary>
        public static string MP_WaitForOtherPlayers {
            get {
                return ResourceManager.GetString("MP_WaitForOtherPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel wird nach der Runde verlassen.
        /// </summary>
        public static string MW_Btn_LeavesAfterMatch {
            get {
                return ResourceManager.GetString("MW_Btn_LeavesAfterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel Verlassen.
        /// </summary>
        public static string MW_LeaveGame {
            get {
                return ResourceManager.GetString("MW_LeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        public static string Newline {
            get {
                return ResourceManager.GetString("Newline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string PlayerCreator_Add {
            get {
                return ResourceManager.GetString("PlayerCreator_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot hinzufügen.
        /// </summary>
        public static string PlayerCreator_AddBot {
            get {
                return ResourceManager.GetString("PlayerCreator_AddBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runter.
        /// </summary>
        public static string PlayerCreator_Down {
            get {
                return ResourceManager.GetString("PlayerCreator_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler Name:.
        /// </summary>
        public static string PlayerCreator_PlayerName {
            get {
                return ResourceManager.GetString("PlayerCreator_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfernen.
        /// </summary>
        public static string PlayerCreator_Remove {
            get {
                return ResourceManager.GetString("PlayerCreator_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel starten.
        /// </summary>
        public static string PlayerCreator_StartGame {
            get {
                return ResourceManager.GetString("PlayerCreator_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoch.
        /// </summary>
        public static string PlayerCreator_Up {
            get {
                return ResourceManager.GetString("PlayerCreator_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontra.
        /// </summary>
        public static string SK_Btn_Kontra {
            get {
                return ResourceManager.GetString("SK_Btn_Kontra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re.
        /// </summary>
        public static string SK_Btn_KontraRe {
            get {
                return ResourceManager.GetString("SK_Btn_KontraRe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Stich.
        /// </summary>
        public static string SK_Btn_LastStich {
            get {
                return ResourceManager.GetString("SK_Btn_LastStich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Runde.
        /// </summary>
        public static string SK_Btn_NewRound {
            get {
                return ResourceManager.GetString("SK_Btn_NewRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte.
        /// </summary>
        public static string SK_Btn_Points {
            get {
                return ResourceManager.GetString("SK_Btn_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aufstellen.
        /// </summary>
        public static string SK_CardHolder_Btn_Aufstellen {
            get {
                return ResourceManager.GetString("SK_CardHolder_Btn_Aufstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 1.
        /// </summary>
        public static string SK_Lbl_Player1 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 2.
        /// </summary>
        public static string SK_Lbl_Player2 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 3.
        /// </summary>
        public static string SK_Lbl_Player3 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 4.
        /// </summary>
        public static string SK_Lbl_Player4 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 5.
        /// </summary>
        public static string SK_Lbl_Player5 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 6.
        /// </summary>
        public static string SK_Lbl_Player6 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 7.
        /// </summary>
        public static string SK_Lbl_Player7 {
            get {
                return ResourceManager.GetString("SK_Lbl_Player7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warten bis alle Spieler wieder da sind.
        /// </summary>
        public static string SK_Lbl_WaitUntilAllPlayerBack {
            get {
                return ResourceManager.GetString("SK_Lbl_WaitUntilAllPlayerBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auf.
        /// </summary>
        public static string SK_PrefixSauspielToString {
            get {
                return ResourceManager.GetString("SK_PrefixSauspielToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenz.
        /// </summary>
        public static string SK_Wenz {
            get {
                return ResourceManager.GetString("SK_Wenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest ansehen.
        /// </summary>
        public static string SKCardHolder_Btn_ShowRemaining {
            get {
                return ResourceManager.GetString("SKCardHolder_Btn_ShowRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel wählen.
        /// </summary>
        public static string SKGameModeSelector_BtnChooseGame {
            get {
                return ResourceManager.GetString("SKGameModeSelector_BtnChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Stich.
        /// </summary>
        public static string SKLastStich_Title {
            get {
                return ResourceManager.GetString("SKLastStich_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aufstellen?.
        /// </summary>
        public static string SKPlayerInfo_Aufstellen {
            get {
                return ResourceManager.GetString("SKPlayerInfo_Aufstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string SKPlayerInfo_empty {
            get {
                return ResourceManager.GetString("SKPlayerInfo_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SKPlayerInfo_Name {
            get {
                return ResourceManager.GetString("SKPlayerInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SKPlayerInfo_Status {
            get {
                return ResourceManager.GetString("SKPlayerInfo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Ansicht drucken.
        /// </summary>
        public static string SKPoints_BtnPrintCurrentView {
            get {
                return ResourceManager.GetString("SKPoints_BtnPrintCurrentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte kumuliert.
        /// </summary>
        public static string SKPoints_TabPointsCumulative {
            get {
                return ResourceManager.GetString("SKPoints_TabPointsCumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte einzeln.
        /// </summary>
        public static string SKPoints_TabPointsSingle {
            get {
                return ResourceManager.GetString("SKPoints_TabPointsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schafkopf Punkte.
        /// </summary>
        public static string SKPoints_Title {
            get {
                return ResourceManager.GetString("SKPoints_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtpunkte.
        /// </summary>
        public static string SKPoints_TotalPoints {
            get {
                return ResourceManager.GetString("SKPoints_TotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schiffe versenken.
        /// </summary>
        public static string SS_BattleShips {
            get {
                return ResourceManager.GetString("SS_BattleShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Gewinnt.
        /// </summary>
        public static string SS_Connect4 {
            get {
                return ResourceManager.GetString("SS_Connect4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kniffel.
        /// </summary>
        public static string SS_Kniffel {
            get {
                return ResourceManager.GetString("SS_Kniffel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto.
        /// </summary>
        public static string SS_Lottery {
            get {
                return ResourceManager.GetString("SS_Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mäxchen.
        /// </summary>
        public static string SS_Maexchen {
            get {
                return ResourceManager.GetString("SS_Maexchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zufallszahlen.
        /// </summary>
        public static string SS_RandomNumberGame {
            get {
                return ResourceManager.GetString("SS_RandomNumberGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schafkopf.
        /// </summary>
        public static string SS_Schafkopf {
            get {
                return ResourceManager.GetString("SS_Schafkopf", resourceCulture);
            }
        }
    }
}
